# Generated by Django 2.2 on 2020-06-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0003_auto_20200625_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Negocio.Direccion'),
            preserve_default=False,
        ),
    ]
