# Generated by Django 2.2 on 2020-06-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0005_auto_20200625_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negocio.Direccion')),
            ],
        ),
    ]
