# Generated by Django 2.2 on 2020-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0006_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='web',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
