# Generated by Django 2.2 on 2020-06-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negocio', '0009_auto_20200625_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='monto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
